### ISSUE TITLE
Error extracting problem date if it is the current date

### ISSUE THREAD

**Issue by woodenstarfish** [EnriqueKhai/Historian#1]
Kattis problems that are solved in the current date will have the following date format: `hh:mm:ss`. The format does not include any other info, and so `datetime.strptime(date, '%Y-%m-%d')` in `extract_first_solved` function in `html_parser.py` causes an error.

**Comment by EnriqueKhai** [comment]
hey vincent! thanks for bringing this to my attention, it was an oversight on my part. good catch!

**Comment by EnriqueKhai** [comment]
issue is fixed, happy scraping!
